DROP TABLE IF EXISTS Account CASCADE;
DROP TABLE IF EXISTS Customer CASCADE;
DROP TABLE IF EXISTS Hotels CASCADE;


CREATE TABLE IF NOT EXISTS Account
(
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(20) UNIQUE NOT NULL,
    name       VARCHAR(20)        NOT NULL,
    password   VARCHAR(20)        NOT NULL,
    security   VARCHAR(20)        NOT NULL,
    answer     VARCHAR(20)        NOT NULL
);

CREATE TABLE IF NOT EXISTS Customer
(
    customer_id INT REFERENCES Account (account_id) ON DELETE CASCADE,
    username    VARCHAR(20) UNIQUE  NOT NULL,
    id          VARCHAR(20)         NOT NULL,
    id_number   VARCHAR(20) UNIQUE  NOT NULL,
    gender      VARCHAR(20)         NOT NULL,
    country     VARCHAR(20)         NOT NULL,
    number      VARCHAR(20)         NOT NULL,
    email       VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Hotels
(
    hotel_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_name  VARCHAR(100) NOT NULL,
    ratings_avg INT,
    phone_num   VARCHAR(20),
    email       VARCHAR(100),
    street_name VARCHAR(255),
    zip_code    VARCHAR(20),
    city        VARCHAR(100),
    country     VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS BookHotel
(
    booking_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id      BIGINT REFERENCES Hotels (hotel_id) ON DELETE CASCADE,
    customer_id   INT REFERENCES Customer (customer_id) ON DELETE CASCADE,
    total_guests  INT            NOT NULL,
    total_rooms   INT            NOT NULL,
    total_cost    DECIMAL(10, 2) NOT NULL,
    food_included VARCHAR(3),
    booking_date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    cost          INT            NOT NULL

);


